### ISSUE TITLE
Unable to install cft package due to dependency

### ISSUE THREAD

**Issue by gjknowlton** [WilliamsTravis/cstdata#154]
I am getting the following errors when installing the cft package: 
 
 ERROR: dependency 'climateR' is not available for package 'cft'
   
I believe this is due to the dependency of the climateR package, which I do not have installed because it is the NPS CCRP policy to only use CRAN-approved packages as dependencies in our workflow (with the exception of cft).

**Comment by ttuff** [comment]
I've made the climateR package an option rather than a dependency. Thanks for point this out.
