### ISSUE TITLE
  could not find function "cftdata"

### ISSUE THREAD

**Issue by nishantsinha5** [WilliamsTravis/cstdata#155]
I am getting the Error in cftdata(aoi = aoi, area_name = "windcave", years = c(2020, 2040),  : 
  could not find function "cftdata"

## I am using the following score:
library(cft)
library(tibble)
library(ggplot2)
library(tidyr)
library(lubridate)
library(ggrepel)
library(dplyr)

proj_dir <- "~" 

aoi <- rgdal::readOGR(system.file("extdata", "windcave.geojson", package = "cft"))

# download data
file_refs <- cftdata(aoi = aoi, 
                     area_name = "windcave",
                     years = c(2020, 2040),
                     local_dir = proj_dir,
                     parameters = c("tasmin", "tasmax", "uas", "vas", "pr"),
                     ncores = parallel::detectCores() / 2)

**Comment by ttuff** [comment]
cftdata has been deprecated because of the downfall of gdal. Please see https://github.com/earthlab/cft/blob/main/vignettes/firehose.md for our replacement.
